version: "3.3"

services:
  backend:
    image: api_cms_game
    build: "./api"
    ports:
      - "8000:8000"
    # command: gunicorn trivia.wsgi -b 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    image: view_cms_game
    build: "./view"
    depends_on:
      - backend
    ports:
      - "80:80"
    # links:
    #   - backend

    # environment:
    #   MONGO_URL: "django://api:8000/"
    # volumen:
    #   - view:/view/build

    # command: python manage.py runserver 0.0.0.0:8000
  # nginx:
  #   image: nginx:1.19.0-alpin
  #   ports:
  #     - 80:80
