version: "3"

services:
  backend:
    image: backend
    build: "./api"
    stdin_open: true
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  frontend:
    image: frontend
    build: "./view"
    depends_on:
      - backend
    ports:
      - "80:8080"
    links:
      - backend

  db:
    image: mysql:5.7
    env_file:
      - ./api/.env
    container_name: mysql_DB
