version: "3.3"

services:
  backend:
    image: backend
    build: "./api"
    stdin_open: true
    ports:
      - "8000:8000"

  frontend:
    image: frontend
    build: "./view"
    depends_on:
      - backend
    ports:
      - "80:80"
    links:
      - backend
