version: "3.3"

services:
  backend:
    image: api_cms_game
    build: "./api"
    ports:
      - "8000:8000"

  frontend:
    image: view_cms_game
    build: "./view"
    depends_on:
      - backend
    ports:
      - "80:80"
    # links:
    #   - backend
