apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
  namespace: default
  resourceVersion: "516"
  uid: b4952dc3-d670-11e5-8cd0-68f728db1985
data:
  game.properties: |
    BACKEND_HOST=http://192.194.99.104:8000
